title: Farty McBallscratcher
description: "Your personal website"
url: https://bbfcfmars.github.io
baseurl: /fartymcballscratcher

# Defaults set by GitHub, only need for local serving
# https://help.github.com/articles/configuring-jekyll/
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# These are GitHub defaults too, but we don't need them
#gems:
#  - jekyll-coffeescript
#  - jekyll-paginate

# Include assets directory
include:
  - assets
  - _layouts
  - _includes

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
